// Code generated by protoc-gen-go. DO NOT EDIT.
// source: portal.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AckCode int32

const (
	AckCode_Success  AckCode = 0
	AckCode_NotLogin AckCode = 1
	AckCode_Error    AckCode = 2
)

var AckCode_name = map[int32]string{
	0: "Success",
	1: "NotLogin",
	2: "Error",
}

var AckCode_value = map[string]int32{
	"Success":  0,
	"NotLogin": 1,
	"Error":    2,
}

func (x AckCode) String() string {
	return proto.EnumName(AckCode_name, int32(x))
}

func (AckCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{0}
}

type HttpRequest struct {
	Method               string                `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string                `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ReqProto             string                `protobuf:"bytes,3,opt,name=req_proto,json=reqProto,proto3" json:"req_proto,omitempty"`
	Header               []*HttpRequest_Header `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty"`
	Body                 []byte                `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Host                 string                `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	RemoteAddr           string                `protobuf:"bytes,7,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HttpRequest) Reset()         { *m = HttpRequest{} }
func (m *HttpRequest) String() string { return proto.CompactTextString(m) }
func (*HttpRequest) ProtoMessage()    {}
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{0}
}

func (m *HttpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequest.Unmarshal(m, b)
}
func (m *HttpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequest.Marshal(b, m, deterministic)
}
func (m *HttpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequest.Merge(m, src)
}
func (m *HttpRequest) XXX_Size() int {
	return xxx_messageInfo_HttpRequest.Size(m)
}
func (m *HttpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequest proto.InternalMessageInfo

func (m *HttpRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HttpRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HttpRequest) GetReqProto() string {
	if m != nil {
		return m.ReqProto
	}
	return ""
}

func (m *HttpRequest) GetHeader() []*HttpRequest_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HttpRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *HttpRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HttpRequest) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

type HttpRequest_Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []string `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpRequest_Header) Reset()         { *m = HttpRequest_Header{} }
func (m *HttpRequest_Header) String() string { return proto.CompactTextString(m) }
func (*HttpRequest_Header) ProtoMessage()    {}
func (*HttpRequest_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{0, 0}
}

func (m *HttpRequest_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequest_Header.Unmarshal(m, b)
}
func (m *HttpRequest_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequest_Header.Marshal(b, m, deterministic)
}
func (m *HttpRequest_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequest_Header.Merge(m, src)
}
func (m *HttpRequest_Header) XXX_Size() int {
	return xxx_messageInfo_HttpRequest_Header.Size(m)
}
func (m *HttpRequest_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequest_Header.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequest_Header proto.InternalMessageInfo

func (m *HttpRequest_Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HttpRequest_Header) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type HttpResponse struct {
	Status               int32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Header               []*HttpRequest_Header `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty"`
	Body                 []byte                `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	NotFinish            bool                  `protobuf:"varint,4,opt,name=not_finish,json=notFinish,proto3" json:"not_finish,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HttpResponse) Reset()         { *m = HttpResponse{} }
func (m *HttpResponse) String() string { return proto.CompactTextString(m) }
func (*HttpResponse) ProtoMessage()    {}
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{1}
}

func (m *HttpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResponse.Unmarshal(m, b)
}
func (m *HttpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResponse.Marshal(b, m, deterministic)
}
func (m *HttpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResponse.Merge(m, src)
}
func (m *HttpResponse) XXX_Size() int {
	return xxx_messageInfo_HttpResponse.Size(m)
}
func (m *HttpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResponse proto.InternalMessageInfo

func (m *HttpResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *HttpResponse) GetHeader() []*HttpRequest_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HttpResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *HttpResponse) GetNotFinish() bool {
	if m != nil {
		return m.NotFinish
	}
	return false
}

type LoginRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RespSeq              int32    `protobuf:"varint,2,opt,name=resp_seq,json=respSeq,proto3" json:"resp_seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetRespSeq() int32 {
	if m != nil {
		return m.RespSeq
	}
	return 0
}

type HeartbeatPkg struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatPkg) Reset()         { *m = HeartbeatPkg{} }
func (m *HeartbeatPkg) String() string { return proto.CompactTextString(m) }
func (*HeartbeatPkg) ProtoMessage()    {}
func (*HeartbeatPkg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{3}
}

func (m *HeartbeatPkg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatPkg.Unmarshal(m, b)
}
func (m *HeartbeatPkg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatPkg.Marshal(b, m, deterministic)
}
func (m *HeartbeatPkg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatPkg.Merge(m, src)
}
func (m *HeartbeatPkg) XXX_Size() int {
	return xxx_messageInfo_HeartbeatPkg.Size(m)
}
func (m *HeartbeatPkg) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatPkg.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatPkg proto.InternalMessageInfo

func (m *HeartbeatPkg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type AckResponse struct {
	Code                 AckCode  `protobuf:"varint,1,opt,name=code,proto3,enum=core.AckCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckResponse) Reset()         { *m = AckResponse{} }
func (m *AckResponse) String() string { return proto.CompactTextString(m) }
func (*AckResponse) ProtoMessage()    {}
func (*AckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{4}
}

func (m *AckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckResponse.Unmarshal(m, b)
}
func (m *AckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckResponse.Marshal(b, m, deterministic)
}
func (m *AckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckResponse.Merge(m, src)
}
func (m *AckResponse) XXX_Size() int {
	return xxx_messageInfo_AckResponse.Size(m)
}
func (m *AckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckResponse proto.InternalMessageInfo

func (m *AckResponse) GetCode() AckCode {
	if m != nil {
		return m.Code
	}
	return AckCode_Success
}

type RpcHeader struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Seq                  int32    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcHeader) Reset()         { *m = RpcHeader{} }
func (m *RpcHeader) String() string { return proto.CompactTextString(m) }
func (*RpcHeader) ProtoMessage()    {}
func (*RpcHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{5}
}

func (m *RpcHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcHeader.Unmarshal(m, b)
}
func (m *RpcHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcHeader.Marshal(b, m, deterministic)
}
func (m *RpcHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcHeader.Merge(m, src)
}
func (m *RpcHeader) XXX_Size() int {
	return xxx_messageInfo_RpcHeader.Size(m)
}
func (m *RpcHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RpcHeader proto.InternalMessageInfo

func (m *RpcHeader) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RpcHeader) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RpcHeader) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func init() {
	proto.RegisterEnum("core.AckCode", AckCode_name, AckCode_value)
	proto.RegisterType((*HttpRequest)(nil), "core.HttpRequest")
	proto.RegisterType((*HttpRequest_Header)(nil), "core.HttpRequest.Header")
	proto.RegisterType((*HttpResponse)(nil), "core.HttpResponse")
	proto.RegisterType((*LoginRequest)(nil), "core.LoginRequest")
	proto.RegisterType((*HeartbeatPkg)(nil), "core.HeartbeatPkg")
	proto.RegisterType((*AckResponse)(nil), "core.AckResponse")
	proto.RegisterType((*RpcHeader)(nil), "core.RpcHeader")
}

func init() { proto.RegisterFile("portal.proto", fileDescriptor_ead6f188e0e8e0b1) }

var fileDescriptor_ead6f188e0e8e0b1 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0xcd, 0x47, 0x9b, 0x49, 0x40, 0x95, 0xb5, 0x42, 0xe6, 0x4b, 0x84, 0x9c, 0x22, 0x84,
	0x4a, 0xb5, 0x9c, 0x39, 0x54, 0x08, 0x54, 0x09, 0x84, 0x56, 0xde, 0x1f, 0x50, 0xb9, 0xf1, 0xb0,
	0xad, 0xda, 0xc4, 0x89, 0xed, 0x20, 0xed, 0x91, 0x33, 0x7f, 0x1a, 0x79, 0x12, 0xa0, 0x17, 0x0e,
	0xdc, 0xde, 0x7b, 0x4e, 0xde, 0xcc, 0x9b, 0x19, 0xc8, 0x3b, 0x6d, 0x9c, 0x3c, 0xaf, 0x3a, 0xa3,
	0x9d, 0x66, 0x51, 0xad, 0x0d, 0x96, 0x3f, 0x66, 0x90, 0x6d, 0x9d, 0xeb, 0x04, 0xf6, 0x03, 0x5a,
	0xc7, 0x1e, 0x43, 0xd2, 0xa0, 0x3b, 0x68, 0xc5, 0x83, 0x22, 0xa8, 0x52, 0x31, 0x31, 0xb6, 0x84,
	0x70, 0x30, 0x67, 0x3e, 0x23, 0xd1, 0x43, 0xf6, 0x0c, 0x52, 0x83, 0xfd, 0x8e, 0xcc, 0x78, 0x48,
	0xfa, 0xc2, 0x60, 0x7f, 0x43, 0xe6, 0x6b, 0x48, 0x0e, 0x28, 0x15, 0x1a, 0x1e, 0x15, 0x61, 0x95,
	0x5d, 0xf3, 0x95, 0xaf, 0xb6, 0xba, 0xa8, 0xb4, 0xda, 0xd2, 0xbb, 0x98, 0xbe, 0x63, 0x0c, 0xa2,
	0xbd, 0x56, 0xf7, 0x3c, 0x2e, 0x82, 0x2a, 0x17, 0x84, 0xbd, 0x76, 0xd0, 0xd6, 0xf1, 0x84, 0xdc,
	0x09, 0xb3, 0x97, 0x90, 0x19, 0x6c, 0xb4, 0xc3, 0x9d, 0x54, 0xca, 0xf0, 0x39, 0x3d, 0xc1, 0x28,
	0x6d, 0x94, 0x32, 0x4f, 0xd7, 0x90, 0x8c, 0xd6, 0xbe, 0xe7, 0x13, 0xde, 0x4f, 0x41, 0x3c, 0x64,
	0x57, 0x10, 0x7f, 0x97, 0xe7, 0x01, 0xf9, 0xac, 0x08, 0xab, 0x54, 0x8c, 0xa4, 0xfc, 0x19, 0x40,
	0x3e, 0x76, 0x66, 0x3b, 0xdd, 0x5a, 0xf4, 0x43, 0xb0, 0x4e, 0xba, 0xc1, 0xd2, 0xbf, 0xb1, 0x98,
	0xd8, 0x45, 0xaa, 0xd9, 0x7f, 0xa6, 0x0a, 0x2f, 0x52, 0xbd, 0x00, 0x68, 0xb5, 0xdb, 0x7d, 0x3b,
	0xb6, 0x47, 0x7b, 0xe0, 0x51, 0x11, 0x54, 0x0b, 0x91, 0xb6, 0xda, 0x7d, 0x22, 0xa1, 0x7c, 0x0f,
	0xf9, 0x17, 0x7d, 0x77, 0x6c, 0x7f, 0x6f, 0x84, 0x41, 0xd4, 0xca, 0x06, 0xa7, 0x18, 0x84, 0xd9,
	0x13, 0x58, 0x18, 0xb4, 0xdd, 0xce, 0x62, 0x4f, 0x2b, 0x89, 0xc5, 0xdc, 0xf3, 0x5b, 0xec, 0xcb,
	0x37, 0x90, 0x6f, 0x51, 0x1a, 0xb7, 0x47, 0xe9, 0x6e, 0x4e, 0x77, 0xec, 0x39, 0xa4, 0xee, 0xd8,
	0xa0, 0x75, 0xb2, 0xe9, 0xc8, 0x23, 0x14, 0x7f, 0x85, 0x72, 0x0d, 0xd9, 0xa6, 0x3e, 0xfd, 0x09,
	0xfe, 0x0a, 0xa2, 0x5a, 0xab, 0xb1, 0xd6, 0xa3, 0xeb, 0x87, 0x63, 0xbc, 0x4d, 0x7d, 0xfa, 0xa0,
	0x15, 0x0a, 0x7a, 0x2a, 0x3f, 0x43, 0x2a, 0xba, 0x7a, 0x9a, 0xf0, 0xbf, 0xae, 0xe5, 0x0a, 0x62,
	0x34, 0x46, 0x9b, 0xe9, 0x5e, 0x46, 0xe2, 0xf7, 0xe1, 0x1b, 0x0e, 0xa9, 0x61, 0x0f, 0x5f, 0xbf,
	0x85, 0xf9, 0xe4, 0xce, 0x32, 0x98, 0xdf, 0x0e, 0x75, 0x8d, 0xd6, 0x2e, 0x1f, 0xb0, 0x1c, 0x16,
	0x5f, 0xb5, 0xa3, 0x31, 0x2c, 0x03, 0x96, 0x42, 0xfc, 0xd1, 0x1b, 0x2c, 0x67, 0xfb, 0x84, 0xce,
	0xed, 0xdd, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xcd, 0xce, 0xdb, 0xcb, 0x02, 0x00, 0x00,
}
